# Load library

In [0]:
#!pip install shap
!pip install pyitlib

In [3]:
from google.colab import drive
drive.mount('/content/drive')
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
your_module = drive.CreateFile({'id':'14_Wk3mGMp53nEiSjMUkeCno_LvRtyQBH'})
your_module.GetContentFile('Bayesian_class.py')
from Bayesian_class import *
import os
os.path.abspath(os.getcwd())
os.chdir('/content/drive/My Drive/Protein project')
os.path.abspath(os.getcwd())


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


'/content/drive/My Drive/Protein project'

### P450

In [0]:
def readData(filename):
	fr = open(filename)
	returnData = []
	headerLine=fr.readline()###move cursor 
	for line in fr.readlines():
		lineStrip = line.strip().replace('"','')
		lineList =	lineStrip.split('\t')
		returnData.append(lineList)###['3','2',...]
	return returnData

"""first case P450 = [['1','1',....],[],[].....,[]]  second case P450 = array([['1','1',....],[],[].....,[]]), third case P450 = """
P450 = readData('P450.txt') ### [[],[],[],....[]]
P450 = np.array(P450) ### either [['1','1',....],[],[].....,[]] or array([['1','1',....],[],[].....,[]]) works, but note that keys are '1', '0' 
#P450 = P450.astype(int) ### for shap array [[1,1,....],[],[].....,[]], keys are 1, 0 

M=np.matrix([[245,   9,   0,   3,   0,   2,  65,   8],
[9, 218,  17,  17,  49,  10,  50,  17],
[0,  17, 175,  16,  25,  13,   0,  46],
[3,  17,  16, 194,  19,   0,   0,   3],
[0,  49,  25,  19, 199,  10,   0,   3],
[2,  10,  13,   0,  10, 249,  50,  74],
[65,  50,   0,   0,   0,  50, 262,  11],
[8,  17,  46,   3,   3,  74,  11, 175]])

X = P450[:,0:8]
y = P450[:,-1]

### Lactamase

In [0]:
def readData2(filename):
	fr = open(filename)
	returnData = []
	headerLine=fr.readline()###move cursor 
	for line in fr.readlines():
		linestr = line.strip().replace(', ','')
		lineList =	list(linestr)
		returnData.append(lineList)###['3','2',...]
	return returnData

lactamase = readData2('lactamase.txt')
lactamase = np.array(lactamase)
#lactamase = lactamase.astype(int)
M2 = np.matrix([[101, 5, 0, 2, 0, 14, 4, 37],
[5 ,15, 14 ,1 ,7 ,7, 0 ,19],
[0, 14, 266, 15, 14, 2, 26, 4],
[2, 1, 15, 28, 2 ,15, 4, 0],
[0, 7, 14, 2, 32, 9 ,0, 8],
[14, 7, 2 ,15, 9, 29, 7, 9],
[4, 0, 26, 4 ,0 ,7 ,72, 21],
[37, 19, 4, 0, 8, 9, 21, 211]])

X2 = lactamase[:,0:8]
y2 = lactamase[:,-1]

### lymph

In [0]:
def readarff(filename):
  arrfFile = open(filename)
  lines = [line.rstrip('\n') for line in arrfFile]
  data = [[]]
  index = 0
  for line in lines :
      if(line.startswith('@attribute')) :
          index+=1
      elif(not line.startswith('@data') and not line.startswith('@relation') and not line.startswith('%')) :
          data.append(line.split(','))
  del data[0]
  return data


lymph_train = readarff("others/lymph_train.arff.txt"); lymph_train = np.array(lymph_train)  
lymph_test = readarff("others/lymph_test.arff.txt") ;lymph_test = np.array(lymph_test)

lymph = np.concatenate((lymph_train,lymph_test))

X10 = lymph[:,0:18]
y10 = lymph[:,-1]

### Vote 

In [0]:
vote_train = readarff("others/vote_train.arff.txt") ;vote_train = np.array(vote_train)
vote_test = readarff("others/vote_test.arff.txt")  ; vote_test = np.array(vote_test)

vote = np.concatenate((vote_train,vote_test))
X11 = vote[:,0:16]
y11 = vote[:,-1]

### german

In [0]:
def readData3(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(' ')
		returnData.append(lineList)###['3','2',...]
	return returnData

german = readData3("data folder/german.data")
german = np.array(german)

X15 = german[:,0:20]
y15 = german[:,-1] 

### balance scale

In [0]:
def readData3(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(',')
		returnData.append(lineList)###['3','2',...]
	return returnData

balance = readData3("data folder/balance-scale.data")
balance = np.array(balance)

X14 = balance[:,1:5]
y14 = balance[:,0] 

### Hayes

In [0]:
def readData3(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(',')
		returnData.append(lineList)###['3','2',...]
	return returnData

hayes = readData3("data folder/hayes-roth.data")
hayes = np.array(hayes)

X13 = hayes[:,1:5] ## remove row index
y13 = hayes[:,-1] 

### mushroom

In [0]:
def readData3(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(',')
		returnData.append(lineList)###['3','2',...]
	return returnData

mushroom = readData3("data folder/agaricus-lepiota.data")
mushroom = np.array(mushroom)

X12 = mushroom[:,1:23]
y12 = mushroom[:,0]  ## first column is y

### connect 4

In [0]:
def readData4(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(',')
		returnData.append(lineList)###['3','2',...]
	return returnData

connect_4 = readData4("data folder/connect-4.data")
connect_4 = np.array(connect_4)

X4 = connect_4[:,0:42]
y4 = connect_4[:,-1] 

### cars

In [0]:
car = readData4("data folder/car.data")
car = np.array(car)
X6 = car[:,0:6]
y6 = car[:,-1] 

### krkopt

In [0]:
krkopt = readData4("data folder/krkopt.data")
krkopt = np.array(krkopt)
X5 = krkopt[:,0:6]
y5 = krkopt[:,-1] 

### Cmc

In [0]:
cmc = readData4("data folder/cmc.data")
cmc = np.array(cmc)
X7 = cmc[:,0:9]
y7 = cmc[:,-1] 

### nurse

In [0]:
def readData3(filename):
	fr = open(filename)
	returnData = []
	for line in fr.readlines():
		lineList = line.strip().split(',')
		returnData.append(lineList)###['3','2',...]
	return returnData

nurse = readData3("data folder/nursery.data")
nurse.pop()
nurse = np.array(nurse)

X3 = nurse[:,0:8]
y3 = nurse[:,-1] 

# Cross validation

### Nurse

In [29]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X3,y3,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9032407407407407 +/- 0.005544828463957304
-491.2840421944758 +/- 9.528281255337598
0.8271603335621501 +/- 0.12848365687770144
0.6779314321996097 +/- 0.05848768124464511
0.681034384813044 +/- 0.060062976863405206
0.22512245349994373 +/- 0.0036386063900404136


In [30]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X3,y3,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9252314814814813 +/- 0.006533174957021425
-318.5272048281944 +/- 13.347704274835602
0.9003266210292564 +/- 0.08900790834420398
0.7118944111209751 +/- 0.05792190739505311
0.7276172654554351 +/- 0.05885445953614209
[2.01450423e+00 2.44729300e-04 8.94450621e-01] +/- [1.98227894e-02 8.83465991e-06 1.22739026e-02]


In [31]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X3,y3,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9260030864197532 +/- 0.006413610695159369
-317.12279005283295 +/- 12.78106883111228
0.9000950285967629 +/- 0.09078824961283169
0.7113520758024816 +/- 0.05892343068612522
0.7262260435053117 +/- 0.059970472376420884
[2.01475148e+00 2.58109850e-04 8.64911496e-01] +/- [3.33739433e-02 2.56098113e-05 1.72967399e-02]


### Cmc

In [25]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X7,y7,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.5091469020040449 +/- 0.03516859547498974
-216.32506865070854 +/- 14.559919963866044
0.5004020786390825 +/- 0.035466995300646106
0.505177358308288 +/- 0.03348558253315055
0.49807854119210154 +/- 0.033607886957029855
0.0202844783999808 +/- 0.0024402531388385824


In [26]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X7,y7,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.4948979591836734 +/- 0.033171538172488316
-242.85756386088173 +/- 17.075563861330163
0.4741251557830483 +/- 0.027965267627108784
0.4657616383897219 +/- 0.028695601119142638
0.4669136347077165 +/- 0.027900827694071234
[5.63207970e-01 3.24047200e-04 3.57634452e-01] +/- [4.89977486e-03 8.42402254e-06 1.69602760e-02]


In [27]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X7,y7,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.5003539253539253 +/- 0.032375090810923546
-236.83709349269662 +/- 15.823884890887795
0.47750365620889934 +/- 0.02928408127420696
0.47061266971134136 +/- 0.028020088614102715
0.47145738180544666 +/- 0.028110239233450345
[5.52587456e-01 3.16893189e-04 3.23279898e-01] +/- [3.09389054e-03 5.49708468e-06 1.89116664e-02]


### krkopt

In [23]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X5,y5,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.36067132691215537 +/- 0.009294949885113833
-7071.700493819822 +/- 58.9681394742186
0.3527022398528179 +/- 0.012146966021181637
0.2920201855758092 +/- 0.009799685838345146
0.2981154724804968 +/- 0.009250940307235354
0.8936855811998612 +/- 0.00797928496278044


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X5,y5,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X5,y5,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


### cars

In [19]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X6,y6,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8454933458798225 +/- 0.022194527441847252
-83.51366633726516 +/- 3.0579111190441455
0.7904139701707026 +/- 0.07644316794424388
0.5607702504831692 +/- 0.05389846045311638
0.6092719930400897 +/- 0.05908094321230245
0.01974008820002382 +/- 0.0015356134292802757


In [20]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X6,y6,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9016534480440919 +/- 0.02287531186529006
-63.40656472163607 +/- 5.589921299611142
0.816861535960465 +/- 0.05984708938690312
0.739870416664675 +/- 0.07753545931767522
0.7582339997412335 +/- 0.07581182028102927
[2.71652440e-01 1.40642600e-04 6.29366681e-02] +/- [5.94967369e-03 5.85964216e-06 7.28980718e-04]


In [21]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X6,y6,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9103306896088185 +/- 0.020630146452423014
-60.51961366446299 +/- 5.030494249164378
0.8728394640306856 +/- 0.04567585366261673
0.7985923765229985 +/- 0.06867216354248641
0.8178393073856036 +/- 0.06332734190523659
[2.68030253e-01 1.40818600e-04 6.03278453e-02] +/- [1.63271162e-03 6.22926962e-06 5.98533178e-04]


###  Mushroom

In [13]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X12,y12,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.954454856124916 +/- 0.009881749328112269
-159.80474565503295 +/- 42.84830733725761
0.9586900991536191 +/- 0.008173689276047542
0.9529569227773729 +/- 0.010271492618481587
0.9541696293737566 +/- 0.01001944200528389
0.20513433150000004 +/- 0.008225277960578706


In [14]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X12,y12,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9918757081659487 +/- 0.0028192308049275307
-31.456317429674083 +/- 13.037255792029248
0.9920707123261054 +/- 0.0026933471835683064
0.9917131642494859 +/- 0.0029124904628502622
0.9918617730005785 +/- 0.0028265277482364326
[9.64752789e+00 3.24111390e-03 1.15221401e+00] +/- [3.22315271e-02 6.05998290e-05 1.74267798e-02]


In [15]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X12,y12,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9931070837801974 +/- 0.0027635875848645926
-17.484832945130844 +/- 6.408445716124378
0.993262902591028 +/- 0.0026378707659454807
0.9929730594086236 +/- 0.0028555591308222932
0.9930956534208925 +/- 0.0027703087949868506
[9.62112553e+00 3.25881956e-03 1.13689991e+00] +/- [1.12391789e-02 1.94189629e-05 1.51365398e-02]


### Hayes

In [9]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X13,y13,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.7961538461538462 +/- 0.09524531530817464
-11.518927454142503 +/- 0.9441731045721156
0.8498941798941798 +/- 0.0701825675545983
0.8255555555555556 +/- 0.08074498799566292
0.8148088948088947 +/- 0.09147896002261661
0.0011568511999998864 +/- 0.00010719075243298276


In [10]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X13,y13,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.6598901098901099 +/- 0.10632826432661631
-12.68687985932818 +/- 2.33906810266788
0.7461700336700336 +/- 0.093639758222384
0.6388888888888888 +/- 0.10222826069121306
0.6421224146224145 +/- 0.10736837347595436
[6.55661411e-02 7.33451000e-05 3.16567620e-03] +/- [4.02695479e-03 6.87047408e-06 1.12118065e-04]


In [11]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X13,y13,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.7126373626373625 +/- 0.13813081905762295
-11.446070523207915 +/- 1.8842216077887763
0.7635113035113036 +/- 0.13843325073140866
0.7077777777777777 +/- 0.12727437068042713
0.7073209198209198 +/- 0.14232685437083223
[6.39666382e-02 7.27721500e-05 3.29695075e-03] +/- [1.53344976e-03 3.16824631e-06 7.62269076e-05]


### balance scale

In [9]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X14,y14,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9136200716845879 +/- 0.012639640680483634
-46.25179475506925 +/- 3.214343783885808
0.6098288502376378 +/- 0.008367593384495194
0.6608374384236454 +/- 0.007773267900521899
0.6341134611670025 +/- 0.008014004415833782
0.0042789363000000245 +/- 0.0004521306543021251


In [10]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X14,y14,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8560419866871479 +/- 0.04004984200081352
-50.07030709299968 +/- 3.2725072278570995
0.5750028690583555 +/- 0.024439096026925778
0.6193349753694581 +/- 0.028805363434701813
0.5951185577435122 +/- 0.026993448719280524
[8.40860301e-02 7.82160000e-05 1.47124575e-02] +/- [1.66487535e-03 7.88583304e-06 3.07728766e-04]


In [11]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X14,y14,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8672555043522785 +/- 0.04253159605379797
-47.56587073454568 +/- 3.3585752131446633
0.5808986142789907 +/- 0.027253065714766597
0.6274220032840723 +/- 0.030874100137352263
0.6020742983414824 +/- 0.029494079962663875
[8.1356839e-02 7.2632050e-05 1.4593128e-02] +/- [1.92391452e-03 4.09509731e-06 2.90515154e-04]


### german

In [12]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X15,y15,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.729 +/- 0.021656407827707735
-80.7912715508979 +/- 7.41564303269633
0.6787826458122943 +/- 0.025064726943812315
0.676904761904762 +/- 0.025355745546119243
0.6765172522333904 +/- 0.02393106964567468
0.026956531300000287 +/- 0.0020367928975791524


In [13]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X15,y15,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.679 +/- 0.03176476034853717
-90.93498171212593 +/- 10.246991967613669
0.5057154045023167 +/- 0.1680783788627454
0.5097619047619047 +/- 0.02873859825180167
0.45539928093532556 +/- 0.05522906157351037
[2.40109816e+00 2.72291540e-03 1.24658065e+01] +/- [2.34895058e-02 7.23575088e-05 9.32855673e-02]


In [14]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X15,y15,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.6860000000000002 +/- 0.02374868417407581
-93.41648211427315 +/- 8.590870259784015
0.49945335407794716 +/- 0.19662184464744042
0.4976190476190476 +/- 0.02467475506291738
0.4300213390588879 +/- 0.03519250525417514
[2.39729962e+00 2.69488945e-03 1.29105709e+01] +/- [8.32977659e-03 1.69845051e-05 1.96407796e-01]


### vote

In [15]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X11,y11,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8964059196617337 +/- 0.06986667297655394
-38.03360399575039 +/- 29.96786557861735
0.8923293096427249 +/- 0.07205606623565262
0.8978197796212501 +/- 0.07379042029180662
0.8918514988466388 +/- 0.07331774584993234
0.010286616699931982 +/- 0.002307549652330903


In [16]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X11,y11,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9308668076109937 +/- 0.06064871812771535
-13.406251847993431 +/- 11.035868177444785
0.9266121388501419 +/- 0.06482782137976167
0.9312992290933468 +/- 0.062295490943305505
0.9278006427351599 +/- 0.06363614873430565
[1.19317227 0.00143497 0.02203004] +/- [1.68632684e-02 2.41397684e-05 3.64844169e-04]


In [17]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X11,y11,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.9308668076109937 +/- 0.06064871812771535
-11.50401590524242 +/- 9.557578647295772
0.9266121388501419 +/- 0.06482782137976167
0.9312992290933468 +/- 0.062295490943305505
0.9278006427351599 +/- 0.06363614873430565
[1.17890588 0.0014036  0.02150373] +/- [5.85259372e-03 5.15725101e-06 2.08553476e-04]


### lymph

In [18]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X10,y10,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8652380952380954 +/- 0.08715846854698506
-7.9499392950203 +/- 4.335192920977545
0.8747619047619049 +/- 0.09000030619191497
0.8574404761904763 +/- 0.08914125217953839
0.860261046143399 +/- 0.08935275809633896
0.005035309400091137 +/- 0.0014805134220000915


In [19]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X10,y10,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8723809523809523 +/- 0.10964382658172321
-8.100204421123111 +/- 3.599898075833295
0.8785515873015873 +/- 0.11337956635853431
0.8636904761904762 +/- 0.11300748475201688
0.8672161743485273 +/- 0.1144422512153267
[1.28129017 0.00193506 0.0126208 ] +/- [1.48097021e-02 3.55969866e-05 2.51461815e-04]


In [20]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X10,y10,None,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8938095238095238 +/- 0.08566268287939177
-7.469120765953927 +/- 3.2054823336408695
0.906998556998557 +/- 0.08289855495218644
0.8845238095238097 +/- 0.09011322872325521
0.8883492152841997 +/- 0.09075285248637355
[1.29169412 0.00198301 0.01354419] +/- [6.66473176e-03 3.62640337e-05 3.40316572e-04]


### P450

In [6]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8030921052631579 +/- 0.04260493671515436
-60.65507027574574 +/- 6.852160443375266
0.8001999322914081 +/- 0.04883139932461019
0.7520414226296579 +/- 0.055884773108179533
0.7643353242392681 +/- 0.05623869751022513
0.010026659100000002 +/- 0.0014269635264082174


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8428837719298246 +/- 0.042267040326305336
-53.132931577474984 +/- 7.72821727713587
0.831042500120207 +/- 0.04770882101844125
0.8265250088305116 +/- 0.040650892755922444
0.8266783872761833 +/- 0.04384578888850275
[3.42133304e-01 2.46560000e-04 2.47645665e-02] +/- [9.27585040e-03 5.49175955e-05 1.60090574e-03]


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.836578947368421 +/- 0.04453364262537665
-52.00175663858268 +/- 7.387766806042236
0.8300733064395089 +/- 0.05227290835214244
0.8025632442615365 +/- 0.05166509144111404
0.8121718017800343 +/- 0.05193434882735014
0.024495523199988156 +/- 0.0016988868471337728


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.85125 +/- 0.04087801651907419
-52.051077907657046 +/- 7.906296962582261
0.8418762644427915 +/- 0.046611367705667775
0.8328936559961229 +/- 0.03931947435656232
0.834927671391052 +/- 0.042123063302941514
[3.41683514e-01 2.30710388e-04 2.42302985e-02] +/- [6.11459794e-03 7.48128779e-06 3.76964590e-04]


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN_bagging,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8386732456140351 +/- 0.04502116206051851
-52.01670852087841 +/- 7.3524008528392475
0.8327930474757874 +/- 0.05275651530810732
0.8041633466680904 +/- 0.052428967935335524
0.8142502546425383 +/- 0.05268231118635524
0.026015597387504384 +/- 0.002843995816254766


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN_TAN_bagging,X,y,M,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8480701754385965 +/- 0.04096166611541898
-50.89744727860291 +/- 7.255657833207949
0.8395895129352123 +/- 0.047539707144283926
0.8227098855182347 +/- 0.04505431989319367
0.8286337065741544 +/- 0.045521480391798916
[3.40071360e-01 2.28813437e-04 2.41500811e-02] +/- [5.89609085e-03 7.57084477e-06 1.63121333e-04]


### lactamase

In [7]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(NB,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8350974025974027 +/- 0.02390300666111667
-29.117813305080336 +/- 3.627485715318661
0.7780625535271082 +/- 0.09077310634817981
0.6371717171717172 +/- 0.05673178616681639
0.6604837505916049 +/- 0.0692982685872787
0.005778308399999954 +/- 0.0009268596402755108


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8857467532467531 +/- 0.046797068658350156
-22.32207330909286 +/- 5.071345485673083
0.8505775783635151 +/- 0.08248741397241535
0.783358585858586 +/- 0.09007851853284064
0.8022699381256869 +/- 0.0845854800201869
[3.02910281e-01 2.27207100e-04 1.42233314e-02] +/- [1.39826157e-02 8.49808301e-06 2.41080040e-04]


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8893181818181818 +/- 0.032289267103993005
-21.040558783947596 +/- 3.0773683408188925
0.862688971129143 +/- 0.060232299547555324
0.7852777777777777 +/- 0.081315409498169
0.8051397350143658 +/- 0.06525825349421391
0.015701663299995516 +/- 0.0020538756570601534


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(TAN_bagging,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8930194805194805 +/- 0.0411411809518517
-21.591852705897015 +/- 4.49934786078972
0.8657090385108474 +/- 0.07943616610612225
0.7947222222222222 +/- 0.07224062508352147
0.8169862265755091 +/- 0.0717046301784505
[2.90292906e-01 2.25829462e-04 1.43157432e-02] +/- [3.81968770e-03 1.07596357e-05 3.92493046e-04]


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN_bagging,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8875324675324675 +/- 0.028305730339377225
-21.01513703024554 +/- 3.1868004567578736
0.8595071885818395 +/- 0.05814694080359701
0.7807323232323232 +/- 0.07424972907786201
0.8018452681343693 +/- 0.06008134356143516
0.01505669208750291 +/- 0.0004686955323256768


In [0]:
Accuracy, CLL, training_time,Precision,Recall,F1 = get_cv(STAN_TAN_bagging,X2,y2,M2,10,verbose=False)
print("%s +/- %s" % (np.mean(Accuracy), np.std(Accuracy) ) )
print("%s +/- %s" % (np.mean(CLL), np.std(CLL) ) )
print("%s +/- %s" % (np.mean(Precision), np.std(Precision) ) )
print("%s +/- %s" % (np.mean(Recall), np.std(Recall) ) )
print("%s +/- %s" % (np.mean(F1), np.std(F1) ) )
print("%s +/- %s" % (np.mean(np.array(training_time),axis=0), np.std(np.array(training_time),axis=0) ) )


0.8930194805194805 +/- 0.03506831693648317
-20.65995308089512 +/- 3.4943010560684433
0.880860818591532 +/- 0.06789834607857566
0.7810858585858587 +/- 0.07641486326910409
0.8082104234351238 +/- 0.06921581282313918
[3.01896152e-01 2.30773025e-04 1.47335994e-02] +/- [4.47847258e-03 4.89053051e-06 1.54512531e-04]
